In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3,4])
b=np.array([5,6,7])
c=np.concatenate((a,b))
print(c)

[1 2 3 4 5 6 7]


In [4]:
d=np.hstack((a,b))
print(d)

[1 2 3 4 5 6 7]


In [9]:
e=np.array([1,2,3,4])
f=np.array([6,7,8,9])
g=np.vstack((e,f))
print(g)

[[1 2 3 4]
 [6 7 8 9]]


In [11]:
h=np.dstack((e,f))
print(h)

[[[1 6]
  [2 7]
  [3 8]
  [4 9]]]


In [12]:
i=np.array_split(e,2)
print(i)

[array([1, 2]), array([3, 4])]


In [16]:
j=np.array_split(f,5)
print(j)

[array([6]), array([7]), array([8]), array([9]), array([], dtype=int32)]


In [17]:
k=np.array_split(f,3)
print(k)

[array([6, 7]), array([8]), array([9])]


In [19]:
print(a.size)

4


In [21]:
l=np.where(d==6)
print(l)

(array([5], dtype=int64),)


In [24]:
m=np.where(d%2==0)
print(m)

(array([1, 3, 5], dtype=int64),)


In [25]:
n=np.where(d%2!=0)
print(n)

(array([0, 2, 4, 6], dtype=int64),)


In [28]:
o=np.searchsorted(d,5,side='left')
print(o)

4


In [29]:
p=np.searchsorted(d,5,side='right')
print(p)

5


In [32]:
q=np.array([1,5,3,7,4,9,10,11,17,12])
r=np.sort(q)
print(r)

[ 1  3  4  5  7  9 10 11 12 17]


In [33]:
s=q>7
t=q[s]
print(t)

[ 9 10 11 17 12]


In [35]:
print(e+f)

[ 7  9 11 13]


In [36]:
print(e-f)

[-5 -5 -5 -5]


In [37]:
print(e*f)

[ 6 14 24 36]


In [38]:
print(e/f)

[0.16666667 0.28571429 0.375      0.44444444]


In [39]:
print(e%f)

[1 2 3 4]


In [40]:
print(e//f)

[0 0 0 0]
