In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [3]:
b=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [4]:
c=np.zeros((3,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
d=np.full((2,2),2)
print(d)

[[2 2]
 [2 2]]


In [6]:
e=np.random.random((4,4))
print(e)

[[0.40387193 0.51227356 0.78737395 0.05281014]
 [0.63362117 0.45100092 0.22684889 0.51619626]
 [0.66743486 0.30597866 0.12640026 0.07910723]
 [0.03135469 0.78320216 0.53175286 0.4977351 ]]


In [7]:
print(b.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
y=b.flatten()
z=y.reshape(4,3)
print(z)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
print(z.dtype)

int32


In [11]:
w=z.astype('complex128')
print(w)

[[ 1.+0.j  2.+0.j  3.+0.j]
 [ 4.+0.j  5.+0.j  6.+0.j]
 [ 7.+0.j  8.+0.j  9.+0.j]
 [10.+0.j 11.+0.j 12.+0.j]]


In [12]:
u=z.astype('float64')
print(u)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [13]:
v=np.arange(5,50,7)
print(v)

[ 5 12 19 26 33 40 47]


In [14]:
print(z[1:,1:])

[[ 5  6]
 [ 8  9]
 [11 12]]


In [17]:
print(z[3,2:])

[12]


In [18]:
print(z[2,1:])

[8 9]
